#### 1. Find Factorial

* Using numpy library and its functions find the factorial of all numbers from 1 till 'n'
* 'n' is the input from the user
* For eg.: Input = 5
* Output should be [1!, 2!, 3!, 4!, 5!] i.e. [1,2,6,24,120]

In [13]:
import numpy as np
import math
n=int(input("Enter no:"))
for x in range (1,n+1):
    y=math.factorial(x)
    print(y)
    

Enter no:8
1
2
6
24
120
720
5040
40320


#### 2. Summarizing our data

* Write a function that returns a summary of our data.
* The function should return
    * Minimum value
    * Maximum Value
    * Mean
    * 1st Quartile i.e. 25th percentile
    * 2nd Quartile i.e. Median
    * 3rd Quartile i.e. 75th percentile
    * Variance
    * Standard Deviation
* Take the data as an input from the csv file using pandas library
* **Note:** .csv file is attached with this notebook.

In [15]:
import pandas as pd
import numpy as np

a = pd.read_csv("./data.csv")
print("Min : ", np.min(a))
print("Max : ", np.max(a))
print("Mean : ", np.mean(a))
print("Quartile 25 pecentile : ",np.quantile(a,0.25))
print("Quartile : ", np.median(a))
print("Quartile 75 percentile : ", np.quantile(a,0.75))
print("Varaince : ", np.var(a))
print("Standard Deviation : ", np.std(a))


Min :  Values    3.32
dtype: float64
Max :  Values    989.0
dtype: float64
Mean :  Values    592.317333
dtype: float64
Quartile 25 pecentile :  416.0
Quartile :  629.5
Quartile 75 percentile :  795.25
Varaince :  Values    75977.038713
dtype: float64
Standard Deviation :  Values    275.639327
dtype: float64


#### 3. Student Report

* Consider the given matrix
    * [45,60,55,70,70,38]<br>[39,48,88,42,37,38]<br>[32,77,60,39,71,38]
    * Here each row stands for marks obtained by a student and each column represents each subject i.e. 3 students and 6 subjects
* Solve following questions for the given marks matrix
    * Per subject how many students failed?
    * How many subjects did each student fail in?
    * What is the highest score in each subject?
    * What is the lowest score in each subject?

In [9]:
import numpy as np
A=np.array([[45,60,55,70,70,38],[39,48,88,42,37,38],[32,77,60,39,71,38]])
print(A)
print("highest score:",A.max())
print("lowest score:",A.min())
print('failed subjects of each student:',np.sum(A<40,axis=1))
print('highest marks in each subject :',np.max(A,axis=0))
print('lowest marks in each subject :',np.min(A,axis=0))

[[45 60 55 70 70 38]
 [39 48 88 42 37 38]
 [32 77 60 39 71 38]]
highest score: 88
lowest score: 32
failed subjects of each student: [1 3 3]
highest marks in each subject : [45 77 88 70 71 38]
lowest marks in each subject : [32 48 55 39 37 38]
