#### 1. EMail Generator
* Write a function to take First Name, Last Name and Date of Birth as input from the user and generate an EMail ID for them.
* The function should return the email id as <br>First two letters of First Name,<br>followed by First letter of Last Name,<br>followed by DOB without '/' followed by '@xyz.com'
* For Eg: **First Name:** Alice , **Last Name:** Garner , **DOB:** 07/11/1995
* Eg Output: alg07111995@xyz.com

In [15]:
fname=input('Enter first name:  ')
lname=input('Enter last name:  ')
dob=input('Enter date of birth in dd/mm/yyyy format:')
L=list(fname[:2])
F=list(lname[:1])
D=list(dob)
D.remove('/')
D.remove('/')
def listtostring(l):
    string=''
    return(string.join(l))
d=listtostring(D)
#print(D)
#res = [int(sub.split('/')[1]) for sub in D]
#print('no are'+str(res))
print(listtostring(L),listtostring(F),d,'@xyz.com')


Enter first name:  pratik
Enter last name:  dhumal
Enter date of birth in dd/mm/yyyy format:07/07/1998
pr d 07071998 @xyz.com


#### 2. Brightness Adjustments

* Intuition: Let us say you have a grayscale image matrix of dimension 3x3<br>[150, 23, 21]<br>[168, 145, 23]<br>[170, 163, 150]<br>we need to reduce the brightness of this image by a factor of 10 i.e. each element of the image matrix should be subtracted by 10. Thus giving us the output image matrix as <br>[140, 13, 11]<br>[158, 135, 13]<br>[160, 153, 140]
* Create a 3x3 matrix having random values between the range of 0 to 255.
* Create a 3x3 matrix having all elements as 10.
* Reduce (Subtraction) the brightness matrix from the image matrix.

In [10]:
import numpy as np
A=np.random.randint(0,255,(3,3))
B=np.full((3, 3),10)
#A = np.array([[150,23,21],[168,145,23],[170,163,150]])
print('Gscale matrix:\n ',A,'\nRedmatrix: \n',B)
C=np.subtract(A,B)
print("\nAfter Reduction matrrix is:\n",C)

Gscale matrix:
  [[166  81 170]
 [234  95  52]
 [ 21 130 156]] 
Redmatrix: 
 [[10 10 10]
 [10 10 10]
 [10 10 10]]

After Reduction matrrix is:
 [[156  71 160]
 [224  85  42]
 [ 11 120 146]]


#### 3. Central Tendency Test

* Intuition: Our goal here is to check the skewness of our distribution.
* Skewness
    * Positively Skewed : Mean > Median
    * Negetively Skewed : Mean < Median
    * Normal Curve : Mean = Median
* Write a function that takes an array of 9 numbers as input and returns the skewness of its distribution.
* Try your function for these inputs
    * Input: [1,2,3,4,5,6,7,8,9] , Expected Output: "Normal Curve"
    * Input: [1,2,3,4,5,6,9,9,10] , Expected Output: "Positively Skewed"
    * Input: [1,1,1,4,5,6,7,8,9] , Expected Output: "Negatively Skewed"
* **Note:** For this test consider the distribution to be sorted in an ascending order. Write code in such a way that even if unsorted array is passed as an input it handles it correctly.

In [16]:
total=0
A = list()
no = 9
print ('Enter 9 numbers in array')
for i in range(int(no)):
    n = input("number :")
    A.append(int(n))
    A.sort()
print ('ARRAY: ',A)
for ele in range(0, len(A)): 
     total= total + A[ele] 
print("Sum of all elements in given list: ", total) 
mean=total/no
print('mean is ',mean)
median=A[4]
print('median is ',median)
if (mean>median):
    print('Distribution is positively skewed')
elif (mean<median):
    print('Distribution is negatively skewed')
else:
    print('Distribution is noraml curve')

Enter 9 numbers in array
number :2
number :4
number :5
number :1
number :7
number :9
number :8
number :3
number :6
ARRAY:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
Sum of all elements in given list:  45
mean is  5.0
median is  5
Distribution is noraml curve


#### 4. Calculating Distances

* Below are two equations for calculating distances between 2 points
    * Euclidean Distance : $\sqrt{(x2 - x1)^2 + (y2-y1)^2}$
    * Manhattan Distance : $ |x2-x1| + |y2-y1| $
* Write a function that takes the x and y coordiantes for two points as inputs and returns the Euclidean and Manhattan distance between the two.

In [26]:
import math
x1=float(input('Enter point x1='))
x2=float(input('Enter point x2='))
y1=float(input('Enter point y1='))
y2=float(input('Enter point y2='))
print("x1=",x1,"\nx2=",x2,"\ny1=",y1,"\ny2=",y2)
E=math.sqrt(((x2-x1)*(x2-x1))+((y2-y1)*(y2-y1)))
print("Euclidean Distance= ",E)
M=abs(x2-x1)+abs(y2-y1)
print("Manhattan Distance= ",M)

Enter point x1=-5
Enter point x2=4
Enter point y1=6
Enter point y2=-2
x1= -5.0 
x2= 4.0 
y1= 6.0 
y2= -2.0
Euclidean Distance=  12.041594578792296
Manhattan Distance=  17.0


#### 5. Softmax Function

* The Softmax Function : $ \frac{e^x}{\sum{e^x}} $
* Create a function that takes a array of numbers as input and returns the probabilities of each element of that array.
* Eg: 
    * Input : [1,2,3]
    * Denominator : e^1 + e^2 + e^3 = 2.71 + 7.38 + 20.08 = 30.16
    * Softmax for each element:
        * e^1/30.16 = 0.089
        * e^2/30.16 = 0.244
        * e^3/30.16 = 0.665

In [23]:
import numpy as np
import math
no=int(input("Enter size:"))
A = []
for i in range(int(no)):
    n = int(input("number :"))
    a=math.exp(n)
    A.append(float(a))
print ('ARRAY: ',A)
C=[sum(A)]
print(C)
S=np.divide(A,C)
print(S)    

Enter size:3
number :1
number :2
number :3
ARRAY:  [2.718281828459045, 7.38905609893065, 20.085536923187668]
[30.19287485057736]
[0.09003057 0.24472847 0.66524096]
