# Sorting

In [27]:
import numpy as np
a=['b','a','d','c','f','e']
np.sort(a)

array(['a', 'b', 'c', 'd', 'e', 'f'], dtype='<U1')

In [17]:
rand=np.random.RandomState(1)
x=rand.randint(0,10,(5,5))
x

array([[5, 8, 9, 5, 0],
       [0, 1, 7, 6, 9],
       [2, 4, 5, 2, 4],
       [2, 4, 7, 7, 9],
       [1, 7, 0, 6, 9]])

In [18]:
np.sort(x,axis=0)#axis=0 is column wise and 1 is row wise

array([[0, 1, 0, 2, 0],
       [1, 4, 5, 5, 4],
       [2, 4, 7, 6, 9],
       [2, 7, 7, 6, 9],
       [5, 8, 9, 7, 9]])

In [13]:
b=np.array([5,6,9,7,1,3,8])
print(np.sort(b))
np.partition(b,0)#here 0 is the index of sorted array

[1 3 5 6 7 8 9]


array([1, 6, 9, 7, 5, 3, 8])

In [26]:
print(x)
print('\n\n',np.sort(x,axis=1),'\n\n')
print(np.partition(x,1,axis=1))

[[5 8 9 5 0]
 [0 1 7 6 9]
 [2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]


 [[0 5 5 8 9]
 [0 1 6 7 9]
 [2 2 4 4 5]
 [2 4 7 7 9]
 [0 1 6 7 9]] 


[[0 5 9 8 5]
 [0 1 7 6 9]
 [2 2 5 4 4]
 [2 4 7 7 9]
 [0 1 7 6 9]]



# Structured array

In [30]:
name=['pratik','taral','hitesh','Shreyashi']
